---
version: 2.1

orbs:
  node: 'circleci/node@4.5.1'

jobs:
  lint:
    executor:
      name: node/default
      tag: 'lts'
    steps:
      - checkout
      - run:
          command: npm ci
      - run:
          command: npm run lint

  test:
    executor:
      name: node/default
      tag: 'lts'
    steps:
      - checkout
      - run:
          command: npm ci
      - run:
          command: npm test

  coverage:
    executor:
      name: node/default
      tag: 'lts'
    steps:
      - checkout
      - run:
          command: npm ci
      - run:
          command: npm test
      - run:
          command: npx c8 report --reporter=html
      - store_artifacts:
          path: coverage

workflows:
  test_my_app:
    jobs:
      - test
      - coverage
